apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: fms22
  namespace : fms-dev
spec:
  selector:
    app: docker-build-test
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: docker-build-test
spec:
  selector:
    matchLabels:
      app: docker-build-test
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: docker-build-test
    spec:
      containers:
        - name: docker-build-test
          image: registry.app.corpintra.net/fms_dtag/fms-java # Image that will be used inside the container in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090 # The port that the container is running on in the cluster